# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.cache/wt [current_project]
set_property parent.project_path F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/AMI.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/BNRZ.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/BRZ.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/CMI.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DataInSyn.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeAMI.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeBNRZ.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeBRZ.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeCMI.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeHDB3.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeMILLER.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeManchester.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeNRZ.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DePST.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/DeRZ.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/E1_Framer.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/HDB3.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/LineCode.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/LineDecode.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/MILLER.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/Manchester.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/NRZ.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/PST.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/base/RZ.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/demultiple.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/dpll_easy.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/pn15.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/driver/uart_rx.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/uart_tx.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/wmy.v
  F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/new/xilinx_wmy.v
}
read_ip -quiet F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all f:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all f:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/constrs_1/new/xilinx_wmy.xdc
set_property used_in_implementation false [get_files F:/WHR/Project/20191111sanjiangbisaiFPGA/wmy/xilinx_wmy.srcs/constrs_1/new/xilinx_wmy.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xilinx_wmy -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_wmy.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xilinx_wmy_utilization_synth.rpt -pb xilinx_wmy_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
